different changes
InventoryManagement2023/InventoryManagement-Backend pull request #11
Opened 2023-05-18 16:24 UTC by martpres

2023-05-20 14:02 UTC, laproksch requested changes

2023-05-20 14:02 UTC, laproksch commented on inventoryManagementWebservice/src/main/java/net/inventorymanagement/inventorymanagementwebservice/facades/InventoryItemFacade.java
>                  String destinationFolder;
@martpres Warum änderst du das Datumsformat hier?

2023-05-20 14:02 UTC, laproksch commented on userControlWebservice/src/main/java/net/inventorymanagement/usercontrolwebservice/configuration/UserControlConfiguration.java
> +                .httpBasic();*/
@martpres Das solltest du nicht commiten. Das ist nur für die lokale Entwicklung gedacht.

2023-05-21 10:16 UTC, martpres commented
In diesem backend feature branch sind keine für den Kamera upload relevanten Änderungen vorhanden gewesen (nur Änderungen um es lokal lauffähig zu machen)

2023-05-21 10:16 UTC, closed without merging